version: '3.8'

services:
  backend:
    build: ./backend
    container_name: doc-reviewer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    
  frontend:
    build: ./frontend
    container_name: doc-reviewer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  uploads: