name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    
    - name: Set environment variables
      run: |
        echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET }}" >> $GITHUB_ENV
        echo "VERSION_LABEL=${{ github.sha }}" >> $GITHUB_ENV
    
    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" "README.md" "*.md"
    
    - name: Upload to S3
      run: |
        aws s3 cp deploy.zip s3://$S3_BUCKET_NAME/deployments/$VERSION_LABEL.zip
    
    - name: Create application version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name zse-doc-reviewer \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=deployments/$VERSION_LABEL.zip
    
    - name: Deploy to environment
      run: |
        aws elasticbeanstalk update-environment \
          --application-name zse-doc-reviewer \ 
          --environment-name zse-doc-reviewer-prod \
          --version-label $VERSION_LABEL \
          --option-settings \
            Namespace=aws:elasticbeanstalk:environment,OptionName=ServiceRole,Value=aws-elasticbeanstalk-service-role
    
    - name: Wait for deployment
      run: |
        aws elasticbeanstalk wait environment-updated \
          --application-name zse-doc-reviewer \
          --environment-name zse-doc-reviewer-prod