name: Deploy to AWS

on:
  push:
    branches:
      - '**'               # any branch
  pull_request:
    branches: [ main ]
    types: [ closed ]      # optional: deploy on merge
  workflow_dispatch:        # manual trigger

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  APPLICATION_NAME: zse-doc-reviewer
  ENV_NAME: zse-doc-reviewer-prod
  HEALTHCHECK_URL: http://zse-doc-reviewer-prod.us-east-1.elasticbeanstalk.com/health

jobs:
  # ----------------------------
  # 1) LINT & SECURITY SCAN
  # ----------------------------
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true   # advisory
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure default branch is available
        run: |
          git fetch origin "${{ github.event.repository.default_branch }}:${{ github.event.repository.default_branch }}"

      - name: Super-Linter
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          VALIDATE_ALL_CODEBASE: true

  # ----------------------------
  # 2) BUILD & UPLOAD TO S3
  # ----------------------------
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set environment variables
        run: |
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET }}" >> $GITHUB_EN
